# Generated by Django 4.2.7 on 2024-01-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geojson', '0002_lines_nominalgeneratorcapacity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lines',
            table='network_links_view',
        ),
        migrations.AlterModelTable(
            name='nominalgeneratorcapacity',
            table='view_nominal_generator_capacity_with_geom',
        ),
        migrations.AlterModelTable(
            name='nominalstoragecapacity',
            table='view_nominal_storage_unit_capacity_with_geom',
        ),
        migrations.AlterModelTable(
            name='optimalgeneratorcapacity',
            table='view_optimal_generator_capacity_with_geom',
        ),
        migrations.AlterModelTable(
            name='optimalstoragecapacity',
            table='view_optimal_storage_unit_capacity_with_geom',
        ),
    ]
