# Generated by Django 4.2.7 on 2024-01-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geojson', '0003_alter_lines_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lines',
            table='network_lines_view',
        ),
    ]
