# Generated by Django 4.2.7 on 2024-02-19 22:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geojson', '0005_remove_bus_json_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
